language: java
node_js:
- '0.10'
env:
- GIT_DEPLOY_DIR: www
script: npm test
after_success:
- git remote set-url origin git@github.com:ultimate-comparisons/ultimate-comparison-BASE.git
- openssl aes-256-cbc -K $encrypted_08460152d0a3_key -iv $encrypted_08460152d0a3_iv -in id_rsa.enc -out id_rsa -d
- in id_rsa.enc -out id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
- "./deploy.sh"
before_install:
- npm install -g npm
- gradle -version
- java -version
- npm -version
- npm install