language: node_js
node_js:
- '6'
env:
- GIT_DEPLOY_DIR: www
script: npm test
after_success:
- git remote set-url origin git@github.com:ultimate-comparisons/ultimate-comparison-BASE.git
- openssl aes-256-cbc -K $encrypted_08460152d0a3_key -iv $encrypted_08460152d0a3_iv -in id_rsa.enc -out id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
- "./deploy.sh"
- "./update.sh"
before_install:
- npm install -g npm
- java -version
- npm -version
- npm install
branches:
  only:
  - master
addons:
  apt_packages:
    - pandoc
    - pandoc-citeproc
sudo: required
dist: trusty